# Generated by Django 3.2.25 on 2024-09-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bvfi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bvfi',
            name='bvbjd',
        ),
        migrations.AddField(
            model_name='bvfi',
            name='bvbjd44',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bvfi',
            name='ytire',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bvfi',
            name='ytuei',
            field=models.BigIntegerField(blank=True),
        ),
    ]
